### ISSUE TITLE
Add thumbnails to saved tabs

### ISSUE THREAD

**Issue by Angelhand** [XFox111/ChromiumTabsAside#1]
todo:get a preview when open the Tab aside instead a black pic

**Comment by XFox111** [comment]
Could you please fix the attached image and give me more details about your suggestion?

**Comment by Angelhand** [comment]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/40990686/78471622-343c7100-7765-11ea-9ef2-99b8155216a6.png">
this，

**Comment by XFox111** [comment]
I've submitted the new version to Chrome Webstore and Microsoft Edge Add-ons Webstore. It will take some time to pass the validation process. For now, you can download v1.2 from [GitHub Releases](https://github.com/XFox111/ChromiumTabsAside/releases/tag/v1.2) and test it.

Note that sideloaded extensions work as completely different ones so they don't interfere with officially installed extensions so you don't have to remove the currently installed version

**Comment by akhilesh-balaji** [comment]
This issue still persists for me, as of now. Here's a screenshot:

![image](https://user-images.githubusercontent.com/69246693/98655163-2b4bf780-2365-11eb-9667-b3762caa4b95.png)

As you can see, it shows shaded boxes instead of the image preview of the website.

Was the extension meant to do this in the first place?
